# Generated by Django 3.0.8 on 2020-07-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0002_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='elevation',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='zip_code',
            field=models.IntegerField(default=100, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trail',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
