# Generated by Django 3.0.8 on 2020-07-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0003_auto_20200729_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='zip_code',
        ),
    ]
